<?php

namespace Database\Seeders;

use App\Models\Etablissement;
use Illuminate\Database\Seeder;

class EtablissementSeeder extends Seeder
{
    public function run(): void
    {
        $etablissements = [
            // CHU
            [
                'nom_fr' => 'Centre Hospitalier Universitaire de Tlemcen',
                'nom_ar' => 'المستشفى الجامعي تلمسان',
                'type' => 'CHU',
                'adresse_fr' => 'Route de l\'Hôpital, Hai Kiffane, Tlemcen',
                'adresse_ar' => 'طريق المستشفى، حي كيفان، تلمسان',
                'telephone' => '043 20 10 00',
                'email' => 'contact@chu-tlemcen.dz',
                'specialites_fr' => 'Médecine interne, Chirurgie générale, Pédiatrie, Gynécologie-obstétrique, Cardiologie, Neurologie, Urgences médico-chirurgicales, Réanimation',
                'specialites_ar' => 'طب داخلي، جراحة عامة، طب الأطفال، أمراض النساء والتوليد، أمراض القلب، طب الأعصاب، الطوارئ الطبية الجراحية، الإنعاش',
                'horaires' => '24h/24 - 7j/7',
                'latitude' => '34.8833',
                'longitude' => '-1.3167',
                'responsable' => 'Pr. Mohammed Benali',
                'is_active' => true,
            ],
            // EPH
            [
                'nom_fr' => 'Etablissement Public Hospitalier de Remchi',
                'nom_ar' => 'المؤسسة العمومية الاستشفائية الرمشي',
                'type' => 'EPH',
                'adresse_fr' => 'Centre-ville, Remchi, Tlemcen',
                'adresse_ar' => 'وسط المدينة، الرمشي، تلمسان',
                'telephone' => '043 25 30 20',
                'email' => 'eph.remchi@dsp-tlemcen.dz',
                'specialites_fr' => 'Médecine générale, Chirurgie, Pédiatrie, Maternité',
                'specialites_ar' => 'طب عام، جراحة، طب أطفال، أمومة',
                'horaires' => '24h/24',
                'latitude' => '35.0583',
                'longitude' => '-1.4333',
                'responsable' => 'Dr. Fatima Zohra Khelifi',
                'is_active' => true,
            ],
            [
                'nom_fr' => 'Etablissement Public Hospitalier de Maghnia',
                'nom_ar' => 'المؤسسة العمومية الاستشفائية مغنية',
                'type' => 'EPH',
                'adresse_fr' => 'Avenue de l\'Indépendance, Maghnia, Tlemcen',
                'adresse_ar' => 'شارع الاستقلال، مغنية، تلمسان',
                'telephone' => '043 30 15 15',
                'email' => 'eph.maghnia@dsp-tlemcen.dz',
                'specialites_fr' => 'Médecine, Chirurgie, Pédiatrie, Urgences',
                'specialites_ar' => 'طب، جراحة، أطفال، طوارئ',
                'horaires' => '24h/24',
                'latitude' => '34.8500',
                'longitude' => '-1.7333',
                'responsable' => 'Dr. Ahmed Benaissa',
                'is_active' => true,
            ],
            // EPSP
            [
                'nom_fr' => 'Etablissement Public de Santé de Proximité de Tlemcen',
                'nom_ar' => 'مؤسسة الصحة الجوارية تلمسان',
                'type' => 'EPSP',
                'adresse_fr' => 'Rue Abane Ramdane, Tlemcen Centre',
                'adresse_ar' => 'شارع عبان رمضان، وسط تلمسان',
                'telephone' => '043 20 55 55',
                'email' => 'epsp.tlemcen@dsp-tlemcen.dz',
                'specialites_fr' => 'Médecine générale, Soins infirmiers, Vaccination, Planning familial',
                'specialites_ar' => 'طب عام، تمريض، تلقيح، تنظيم الأسرة',
                'horaires' => 'Dim-Jeu : 08h00-16h30',
                'latitude' => '34.8800',
                'longitude' => '-1.3100',
                'responsable' => 'Dr. Nadia Mekki',
                'is_active' => true,
            ],
            [
                'nom_fr' => 'Etablissement Public de Santé de Proximité de Chetouane',
                'nom_ar' => 'مؤسسة الصحة الجوارية شتوان',
                'type' => 'EPSP',
                'adresse_fr' => 'Cité des Frères Bouazza, Chetouane, Tlemcen',
                'adresse_ar' => 'حي الإخوة بوعزة، شتوان، تلمسان',
                'telephone' => '043 22 40 40',
                'email' => 'epsp.chetouane@dsp-tlemcen.dz',
                'specialites_fr' => 'Médecine générale, Soins dentaires, Analyses médicales',
                'specialites_ar' => 'طب عام، عناية أسنان، تحاليل طبية',
                'horaires' => 'Dim-Jeu : 08h00-16h30',
                'latitude' => '34.9200',
                'longitude' => '-1.2900',
                'responsable' => 'Dr. Karim Djellali',
                'is_active' => true,
            ],
            // Polycliniques
            [
                'nom_fr' => 'Polyclinique d\'Imama',
                'nom_ar' => 'مصحة إمامة',
                'type' => 'Polyclinique',
                'adresse_fr' => 'Cité Imama, Tlemcen',
                'adresse_ar' => 'حي إمامة، تلمسان',
                'telephone' => '043 21 30 30',
                'email' => null,
                'specialites_fr' => 'Médecine générale, Dentiste, Maternité, Analyses',
                'specialites_ar' => 'طب عام، أسنان، أمومة، تحاليل',
                'horaires' => 'Dim-Jeu : 08h00-16h30',
                'latitude' => '34.8900',
                'longitude' => '-1.3000',
                'responsable' => 'Dr. Amina Ferhat',
                'is_active' => true,
            ],
            [
                'nom_fr' => 'Polyclinique de Mansourah',
                'nom_ar' => 'مصحة منصورة',
                'type' => 'Polyclinique',
                'adresse_fr' => 'Rue de la Révolution, Mansourah, Tlemcen',
                'adresse_ar' => 'شارع الثورة، منصورة، تلمسان',
                'telephone' => '043 21 40 40',
                'email' => null,
                'specialites_fr' => 'Médecine générale, Pédiatrie, Gynécologie',
                'specialites_ar' => 'طب عام، أطفال، نساء',
                'horaires' => 'Dim-Jeu : 08h00-16h30',
                'latitude' => '34.8700',
                'longitude' => '-1.3400',
                'responsable' => null,
                'is_active' => true,
            ],
            [
                'nom_fr' => 'Polyclinique de Kiffane',
                'nom_ar' => 'مصحة كيفان',
                'type' => 'Polyclinique',
                'adresse_fr' => 'Hai Kiffane, Tlemcen',
                'adresse_ar' => 'حي كيفان، تلمسان',
                'telephone' => '043 21 50 50',
                'email' => null,
                'specialites_fr' => 'Médecine générale, Cardiologie, Diabétologie',
                'specialites_ar' => 'طب عام، قلب، سكري',
                'horaires' => 'Dim-Jeu : 08h00-16h30',
                'latitude' => '34.8850',
                'longitude' => '-1.3150',
                'responsable' => null,
                'is_active' => true,
            ],
            // Salles de soins
            [
                'nom_fr' => 'Salle de soins de Birouana',
                'nom_ar' => 'قاعة العلاج بيروانة',
                'type' => 'Salle de soins',
                'adresse_fr' => 'Village Birouana, Tlemcen',
                'adresse_ar' => 'قرية بيروانة، تلمسان',
                'telephone' => null,
                'email' => null,
                'specialites_fr' => 'Soins infirmiers, Vaccination',
                'specialites_ar' => 'تمريض، تلقيح',
                'horaires' => 'Dim-Jeu : 08h00-14h00',
                'latitude' => '34.8600',
                'longitude' => '-1.3500',
                'responsable' => null,
                'is_active' => true,
            ],
            [
                'nom_fr' => 'Salle de soins de Sidi Boumediene',
                'nom_ar' => 'قاعة العلاج سيدي بومدين',
                'type' => 'Salle de soins',
                'adresse_fr' => 'Sidi Boumediene, Tlemcen',
                'adresse_ar' => 'سيدي بومدين، تلمسان',
                'telephone' => null,
                'email' => null,
                'specialites_fr' => 'Soins infirmiers, Suivi des maladies chroniques',
                'specialites_ar' => 'تمريض، متابعة الأمراض المزمنة',
                'horaires' => 'Dim-Jeu : 08h00-14h00',
                'latitude' => '34.8950',
                'longitude' => '-1.2950',
                'responsable' => null,
                'is_active' => true,
            ],
            // Urgences
            [
                'nom_fr' => 'Service des Urgences Médico-Chirurgicales CHU Tlemcen',
                'nom_ar' => 'مصلحة الطوارئ الطبية الجراحية - المستشفى الجامعي تلمسان',
                'type' => 'Urgence',
                'adresse_fr' => 'CHU Tlemcen, Route de l\'Hôpital',
                'adresse_ar' => 'المستشفى الجامعي تلمسان، طريق المستشفى',
                'telephone' => '043 20 10 01',
                'email' => null,
                'specialites_fr' => 'Urgences médicales, Urgences chirurgicales, Réanimation',
                'specialites_ar' => 'طوارئ طبية، طوارئ جراحية، إنعاش',
                'horaires' => '24h/24',
                'latitude' => '34.8835',
                'longitude' => '-1.3165',
                'responsable' => 'Pr. Abdelkader Henni',
                'is_active' => true,
            ],
            // Maternités
            [
                'nom_fr' => 'Maternité du CHU Tlemcen',
                'nom_ar' => 'مصلحة الأمومة - المستشفى الجامعي تلمسان',
                'type' => 'Maternité',
                'adresse_fr' => 'CHU Tlemcen, Route de l\'Hôpital',
                'adresse_ar' => 'المستشفى الجامعي تلمسان، طريق المستشفى',
                'telephone' => '043 20 10 20',
                'email' => null,
                'specialites_fr' => 'Obstétrique, Gynécologie, Néonatologie',
                'specialites_ar' => 'توليد، نساء، حديثي الولادة',
                'horaires' => '24h/24',
                'latitude' => '34.8832',
                'longitude' => '-1.3162',
                'responsable' => 'Pr. Fatiha Bouzid',
                'is_active' => true,
            ],
        ];

        foreach ($etablissements as $etab) {
            Etablissement::create($etab);
        }
    }
}
